services:
  db:
    image: postgis/postgis:15-3.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d geoportal"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: geoportal
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d  # The "Magic" mapping
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gis-network
    ports:
      - "${DB_HOST_PORT}:5432"

# tileserv: Ideal for vectors (Strems winds etc)
  tileserver: # TODO: IMPORTANT: Check: Probably need to replace/extend this with pg_titiler 
    image: pramsey/pg_tileserv:latest # Or neteler/postgis-t-rex # Or crunchydata/pg_tileserv
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD_URL}@db:5432/geoportal
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    restart: on-failure  # Add this
    depends_on:
      db:
        condition: service_healthy # Waits for healthcheck to pass
    networks:
      - gis-network
    ports:
      - "${TILESERV_HOST_PORT}:7800"

  # The "Brain" for caching
  redis:
    image: redis:7-alpine
    networks:
      - gis-network
    # Persist cache even if container restarts
    # command: redis-server --save 60 1 --loglevel warning
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
      --tcp-keepalive 60
      --loglevel warning

  # Tttiler: Ideal for image and various hirarchies of image
  raster-server:
    image: ghcr.io/developmentseed/titiler:latest
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD_URL}@db:5432/geoportal
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      # Tell TiTiler to use Redis
      TITILER_CACHE_TYPE: redis
      TITILER_CACHE_REDIS_URL: redis://redis:6379/0
      # Cache tiles for 24 hours (in seconds)
      TITILER_CACHE_EXPIRE: 86400
    volumes:
      - ./data:/data
    ports:
      - "${TITILER_HOST_PORT}:80"
    networks:
      - gis-network

  backend:
    build:
      context: ./backend
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD_URL}@db:5432/geoportal
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PASSWORD_URL: ${DB_PASSWORD_URL}
    restart: on-failure  # This restarts the service automatically
    depends_on:
      db:
        condition: service_healthy # Waits for healthcheck to pass
    networks:
      - gis-network

networks:
  gis-network:
    driver: bridge

volumes:
  postgres_data: